configuration :
    log :
        enabled : true
        handler : RotatingFile

templates :
    - plugin  : random
      filename : random
      enabled : true
      arguments :
          min : 5
          max : 10