configuration :
    log :
        enabled : true
        handler : RotatingFile

graphs :
    - template : random
      enabled : true
      arguments :
          min : 5
          max : 10
          
    - template : system_load
      enabled : true
      
    - template : weather_google
      enabled : true
      arguments :
          location : Istanbul,Turkey
          type : c

    - template : system_loggedusers
      enabled : true
      
    - template : network_tcpconnections
      enabled : true